language: java
sudo: true
jdk:
- openjdk8
install: true
script: ./gradle/buildViaTravis.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_8b97babf59d5_key -iv $encrypted_8b97babf59d5_iv
  -in gradle.properties.enc -out gradle.properties -d || true
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
